version: '3.5'

services:

  health_checker:
    build: .
    image: abilioesteves/health-checker:latest
    ports:
      - "37441:37441"
    environment:
      - HC_PORT=37441
      - HC_LOG_LEVEL=debug
      - HC_TARGET_HEALTH_URL=http://localhost:37441/health
      - HC_TARGET_NAME="Health Checker"
    restart: on-failure